package com.example.demo.entity;

public class TbCar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_car.car_id
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private Integer carId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_car.car_type
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private String carType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_car.car_plate_number
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private String carPlateNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_car.car_color
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private String carColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_car.car_type_model
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private String carTypeModel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_car.column_6
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private Integer column6;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_car
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public TbCar(Integer carId, String carType, String carPlateNumber, String carColor, String carTypeModel, Integer column6) {
        this.carId = carId;
        this.carType = carType;
        this.carPlateNumber = carPlateNumber;
        this.carColor = carColor;
        this.carTypeModel = carTypeModel;
        this.column6 = column6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_car
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public TbCar() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_car.car_id
     *
     * @return the value of tb_car.car_id
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_car.car_id
     *
     * @param carId the value for tb_car.car_id
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_car.car_type
     *
     * @return the value of tb_car.car_type
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_car.car_type
     *
     * @param carType the value for tb_car.car_type
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setCarType(String carType) {
        this.carType = carType == null ? null : carType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_car.car_plate_number
     *
     * @return the value of tb_car.car_plate_number
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public String getCarPlateNumber() {
        return carPlateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_car.car_plate_number
     *
     * @param carPlateNumber the value for tb_car.car_plate_number
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setCarPlateNumber(String carPlateNumber) {
        this.carPlateNumber = carPlateNumber == null ? null : carPlateNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_car.car_color
     *
     * @return the value of tb_car.car_color
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public String getCarColor() {
        return carColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_car.car_color
     *
     * @param carColor the value for tb_car.car_color
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setCarColor(String carColor) {
        this.carColor = carColor == null ? null : carColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_car.car_type_model
     *
     * @return the value of tb_car.car_type_model
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public String getCarTypeModel() {
        return carTypeModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_car.car_type_model
     *
     * @param carTypeModel the value for tb_car.car_type_model
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setCarTypeModel(String carTypeModel) {
        this.carTypeModel = carTypeModel == null ? null : carTypeModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_car.column_6
     *
     * @return the value of tb_car.column_6
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public Integer getColumn6() {
        return column6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_car.column_6
     *
     * @param column6 the value for tb_car.column_6
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setColumn6(Integer column6) {
        this.column6 = column6;
    }
}