package com.example.demo.entity;

import java.util.Date;

public class TbCarUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_car_user.car_user_id
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private Integer carUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_car_user.user_id
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_car_user.car_id
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private Integer carId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_car_user.car_user_last_time
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private Date carUserLastTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_car_user.car_user_parking_space
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private String carUserParkingSpace;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_car_user
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public TbCarUser(Integer carUserId, Integer userId, Integer carId, Date carUserLastTime, String carUserParkingSpace) {
        this.carUserId = carUserId;
        this.userId = userId;
        this.carId = carId;
        this.carUserLastTime = carUserLastTime;
        this.carUserParkingSpace = carUserParkingSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_car_user
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public TbCarUser() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_car_user.car_user_id
     *
     * @return the value of tb_car_user.car_user_id
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public Integer getCarUserId() {
        return carUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_car_user.car_user_id
     *
     * @param carUserId the value for tb_car_user.car_user_id
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setCarUserId(Integer carUserId) {
        this.carUserId = carUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_car_user.user_id
     *
     * @return the value of tb_car_user.user_id
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_car_user.user_id
     *
     * @param userId the value for tb_car_user.user_id
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_car_user.car_id
     *
     * @return the value of tb_car_user.car_id
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_car_user.car_id
     *
     * @param carId the value for tb_car_user.car_id
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_car_user.car_user_last_time
     *
     * @return the value of tb_car_user.car_user_last_time
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public Date getCarUserLastTime() {
        return carUserLastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_car_user.car_user_last_time
     *
     * @param carUserLastTime the value for tb_car_user.car_user_last_time
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setCarUserLastTime(Date carUserLastTime) {
        this.carUserLastTime = carUserLastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_car_user.car_user_parking_space
     *
     * @return the value of tb_car_user.car_user_parking_space
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public String getCarUserParkingSpace() {
        return carUserParkingSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_car_user.car_user_parking_space
     *
     * @param carUserParkingSpace the value for tb_car_user.car_user_parking_space
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setCarUserParkingSpace(String carUserParkingSpace) {
        this.carUserParkingSpace = carUserParkingSpace == null ? null : carUserParkingSpace.trim();
    }
}