package com.example.demo.entity;

import java.util.Date;

public class TbMonthlyCard {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_monthly_card.monthly_card_id
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private Integer monthlyCardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_monthly_card.monthly_card_location
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private String monthlyCardLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_monthly_card.monthly_card_usage_count
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private Integer monthlyCardUsageCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_monthly_card.monthly_card_start_time
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private Date monthlyCardStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_monthly_card.monthly_card_end_time
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private Date monthlyCardEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_monthly_card.monthly_card_usage_rule
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private Integer monthlyCardUsageRule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_monthly_card.monthly_card_release_time
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private Date monthlyCardReleaseTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_monthly_card
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public TbMonthlyCard(Integer monthlyCardId, String monthlyCardLocation, Integer monthlyCardUsageCount, Date monthlyCardStartTime, Date monthlyCardEndTime, Integer monthlyCardUsageRule, Date monthlyCardReleaseTime) {
        this.monthlyCardId = monthlyCardId;
        this.monthlyCardLocation = monthlyCardLocation;
        this.monthlyCardUsageCount = monthlyCardUsageCount;
        this.monthlyCardStartTime = monthlyCardStartTime;
        this.monthlyCardEndTime = monthlyCardEndTime;
        this.monthlyCardUsageRule = monthlyCardUsageRule;
        this.monthlyCardReleaseTime = monthlyCardReleaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_monthly_card
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public TbMonthlyCard() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_monthly_card.monthly_card_id
     *
     * @return the value of tb_monthly_card.monthly_card_id
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public Integer getMonthlyCardId() {
        return monthlyCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_monthly_card.monthly_card_id
     *
     * @param monthlyCardId the value for tb_monthly_card.monthly_card_id
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setMonthlyCardId(Integer monthlyCardId) {
        this.monthlyCardId = monthlyCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_monthly_card.monthly_card_location
     *
     * @return the value of tb_monthly_card.monthly_card_location
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public String getMonthlyCardLocation() {
        return monthlyCardLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_monthly_card.monthly_card_location
     *
     * @param monthlyCardLocation the value for tb_monthly_card.monthly_card_location
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setMonthlyCardLocation(String monthlyCardLocation) {
        this.monthlyCardLocation = monthlyCardLocation == null ? null : monthlyCardLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_monthly_card.monthly_card_usage_count
     *
     * @return the value of tb_monthly_card.monthly_card_usage_count
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public Integer getMonthlyCardUsageCount() {
        return monthlyCardUsageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_monthly_card.monthly_card_usage_count
     *
     * @param monthlyCardUsageCount the value for tb_monthly_card.monthly_card_usage_count
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setMonthlyCardUsageCount(Integer monthlyCardUsageCount) {
        this.monthlyCardUsageCount = monthlyCardUsageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_monthly_card.monthly_card_start_time
     *
     * @return the value of tb_monthly_card.monthly_card_start_time
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public Date getMonthlyCardStartTime() {
        return monthlyCardStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_monthly_card.monthly_card_start_time
     *
     * @param monthlyCardStartTime the value for tb_monthly_card.monthly_card_start_time
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setMonthlyCardStartTime(Date monthlyCardStartTime) {
        this.monthlyCardStartTime = monthlyCardStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_monthly_card.monthly_card_end_time
     *
     * @return the value of tb_monthly_card.monthly_card_end_time
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public Date getMonthlyCardEndTime() {
        return monthlyCardEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_monthly_card.monthly_card_end_time
     *
     * @param monthlyCardEndTime the value for tb_monthly_card.monthly_card_end_time
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setMonthlyCardEndTime(Date monthlyCardEndTime) {
        this.monthlyCardEndTime = monthlyCardEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_monthly_card.monthly_card_usage_rule
     *
     * @return the value of tb_monthly_card.monthly_card_usage_rule
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public Integer getMonthlyCardUsageRule() {
        return monthlyCardUsageRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_monthly_card.monthly_card_usage_rule
     *
     * @param monthlyCardUsageRule the value for tb_monthly_card.monthly_card_usage_rule
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setMonthlyCardUsageRule(Integer monthlyCardUsageRule) {
        this.monthlyCardUsageRule = monthlyCardUsageRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_monthly_card.monthly_card_release_time
     *
     * @return the value of tb_monthly_card.monthly_card_release_time
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public Date getMonthlyCardReleaseTime() {
        return monthlyCardReleaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_monthly_card.monthly_card_release_time
     *
     * @param monthlyCardReleaseTime the value for tb_monthly_card.monthly_card_release_time
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setMonthlyCardReleaseTime(Date monthlyCardReleaseTime) {
        this.monthlyCardReleaseTime = monthlyCardReleaseTime;
    }
}