package com.example.demo.entity;

public class TbParkingLot {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_parking_lot.id
     *
     * @mbg.generated Fri Apr 17 19:17:36 GMT+08:00 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_parking_lot.parking_lot_name
     *
     * @mbg.generated Fri Apr 17 19:17:36 GMT+08:00 2020
     */
    private String parkingLotName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_parking_lot.space_number
     *
     * @mbg.generated Fri Apr 17 19:17:36 GMT+08:00 2020
     */
    private Integer spaceNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_parking_lot.fixed_parking_num
     *
     * @mbg.generated Fri Apr 17 19:17:36 GMT+08:00 2020
     */
    private Integer fixedParkingNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_parking_lot.parking_lot_level
     *
     * @mbg.generated Fri Apr 17 19:17:36 GMT+08:00 2020
     */
    private String parkingLotLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_parking_lot.pay_setting
     *
     * @mbg.generated Fri Apr 17 19:17:36 GMT+08:00 2020
     */
    private String paySetting;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_parking_lot.print_setting
     *
     * @mbg.generated Fri Apr 17 19:17:36 GMT+08:00 2020
     */
    private String printSetting;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_parking_lot.rule_setting
     *
     * @mbg.generated Fri Apr 17 19:17:36 GMT+08:00 2020
     */
    private String ruleSetting;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_parking_lot
     *
     * @mbg.generated Fri Apr 17 19:17:36 GMT+08:00 2020
     */
    public TbParkingLot(Integer id, String parkingLotName, Integer spaceNumber, Integer fixedParkingNum, String parkingLotLevel, String paySetting, String printSetting, String ruleSetting) {
        this.id = id;
        this.parkingLotName = parkingLotName;
        this.spaceNumber = spaceNumber;
        this.fixedParkingNum = fixedParkingNum;
        this.parkingLotLevel = parkingLotLevel;
        this.paySetting = paySetting;
        this.printSetting = printSetting;
        this.ruleSetting = ruleSetting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_parking_lot
     *
     * @mbg.generated Fri Apr 17 19:17:36 GMT+08:00 2020
     */
    public TbParkingLot() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_parking_lot.id
     *
     * @return the value of tb_parking_lot.id
     *
     * @mbg.generated Fri Apr 17 19:17:36 GMT+08:00 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_parking_lot.id
     *
     * @param id the value for tb_parking_lot.id
     *
     * @mbg.generated Fri Apr 17 19:17:36 GMT+08:00 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_parking_lot.parking_lot_name
     *
     * @return the value of tb_parking_lot.parking_lot_name
     *
     * @mbg.generated Fri Apr 17 19:17:36 GMT+08:00 2020
     */
    public String getParkingLotName() {
        return parkingLotName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_parking_lot.parking_lot_name
     *
     * @param parkingLotName the value for tb_parking_lot.parking_lot_name
     *
     * @mbg.generated Fri Apr 17 19:17:36 GMT+08:00 2020
     */
    public void setParkingLotName(String parkingLotName) {
        this.parkingLotName = parkingLotName == null ? null : parkingLotName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_parking_lot.space_number
     *
     * @return the value of tb_parking_lot.space_number
     *
     * @mbg.generated Fri Apr 17 19:17:36 GMT+08:00 2020
     */
    public Integer getSpaceNumber() {
        return spaceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_parking_lot.space_number
     *
     * @param spaceNumber the value for tb_parking_lot.space_number
     *
     * @mbg.generated Fri Apr 17 19:17:36 GMT+08:00 2020
     */
    public void setSpaceNumber(Integer spaceNumber) {
        this.spaceNumber = spaceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_parking_lot.fixed_parking_num
     *
     * @return the value of tb_parking_lot.fixed_parking_num
     *
     * @mbg.generated Fri Apr 17 19:17:36 GMT+08:00 2020
     */
    public Integer getFixedParkingNum() {
        return fixedParkingNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_parking_lot.fixed_parking_num
     *
     * @param fixedParkingNum the value for tb_parking_lot.fixed_parking_num
     *
     * @mbg.generated Fri Apr 17 19:17:36 GMT+08:00 2020
     */
    public void setFixedParkingNum(Integer fixedParkingNum) {
        this.fixedParkingNum = fixedParkingNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_parking_lot.parking_lot_level
     *
     * @return the value of tb_parking_lot.parking_lot_level
     *
     * @mbg.generated Fri Apr 17 19:17:36 GMT+08:00 2020
     */
    public String getParkingLotLevel() {
        return parkingLotLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_parking_lot.parking_lot_level
     *
     * @param parkingLotLevel the value for tb_parking_lot.parking_lot_level
     *
     * @mbg.generated Fri Apr 17 19:17:36 GMT+08:00 2020
     */
    public void setParkingLotLevel(String parkingLotLevel) {
        this.parkingLotLevel = parkingLotLevel == null ? null : parkingLotLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_parking_lot.pay_setting
     *
     * @return the value of tb_parking_lot.pay_setting
     *
     * @mbg.generated Fri Apr 17 19:17:36 GMT+08:00 2020
     */
    public String getPaySetting() {
        return paySetting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_parking_lot.pay_setting
     *
     * @param paySetting the value for tb_parking_lot.pay_setting
     *
     * @mbg.generated Fri Apr 17 19:17:36 GMT+08:00 2020
     */
    public void setPaySetting(String paySetting) {
        this.paySetting = paySetting == null ? null : paySetting.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_parking_lot.print_setting
     *
     * @return the value of tb_parking_lot.print_setting
     *
     * @mbg.generated Fri Apr 17 19:17:36 GMT+08:00 2020
     */
    public String getPrintSetting() {
        return printSetting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_parking_lot.print_setting
     *
     * @param printSetting the value for tb_parking_lot.print_setting
     *
     * @mbg.generated Fri Apr 17 19:17:36 GMT+08:00 2020
     */
    public void setPrintSetting(String printSetting) {
        this.printSetting = printSetting == null ? null : printSetting.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_parking_lot.rule_setting
     *
     * @return the value of tb_parking_lot.rule_setting
     *
     * @mbg.generated Fri Apr 17 19:17:36 GMT+08:00 2020
     */
    public String getRuleSetting() {
        return ruleSetting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_parking_lot.rule_setting
     *
     * @param ruleSetting the value for tb_parking_lot.rule_setting
     *
     * @mbg.generated Fri Apr 17 19:17:36 GMT+08:00 2020
     */
    public void setRuleSetting(String ruleSetting) {
        this.ruleSetting = ruleSetting == null ? null : ruleSetting.trim();
    }

    @Override
    public String
    toString() {
        return "TbParkingLot{" +
                "id=" + id +
                ", parkingLotName='" + parkingLotName + '\'' +
                ", spaceNumber=" + spaceNumber +
                ", fixedParkingNum=" + fixedParkingNum +
                ", parkingLotLevel='" + parkingLotLevel + '\'' +
                ", paySetting='" + paySetting + '\'' +
                ", printSetting='" + printSetting + '\'' +
                ", ruleSetting='" + ruleSetting + '\'' +
                '}';
    }
}