package com.example.demo.entity;

import java.util.Date;

public class TbParkingRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_parking_record.parking_plate_id
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private Integer parkingPlateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_parking_record.car_plate_num
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private String carPlateNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_parking_record.enter_time
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private Date enterTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_parking_record.exit_time
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private Date exitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_parking_record.last_time
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private String lastTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_parking_record.order_id
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private Integer orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_parking_record
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public TbParkingRecord(Integer parkingPlateId, String carPlateNum, Date enterTime, Date exitTime, String lastTime, Integer orderId) {
        this.parkingPlateId = parkingPlateId;
        this.carPlateNum = carPlateNum;
        this.enterTime = enterTime;
        this.exitTime = exitTime;
        this.lastTime = lastTime;
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_parking_record
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public TbParkingRecord() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_parking_record.parking_plate_id
     *
     * @return the value of tb_parking_record.parking_plate_id
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public Integer getParkingPlateId() {
        return parkingPlateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_parking_record.parking_plate_id
     *
     * @param parkingPlateId the value for tb_parking_record.parking_plate_id
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setParkingPlateId(Integer parkingPlateId) {
        this.parkingPlateId = parkingPlateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_parking_record.car_plate_num
     *
     * @return the value of tb_parking_record.car_plate_num
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public String getCarPlateNum() {
        return carPlateNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_parking_record.car_plate_num
     *
     * @param carPlateNum the value for tb_parking_record.car_plate_num
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setCarPlateNum(String carPlateNum) {
        this.carPlateNum = carPlateNum == null ? null : carPlateNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_parking_record.enter_time
     *
     * @return the value of tb_parking_record.enter_time
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public Date getEnterTime() {
        return enterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_parking_record.enter_time
     *
     * @param enterTime the value for tb_parking_record.enter_time
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setEnterTime(Date enterTime) {
        this.enterTime = enterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_parking_record.exit_time
     *
     * @return the value of tb_parking_record.exit_time
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public Date getExitTime() {
        return exitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_parking_record.exit_time
     *
     * @param exitTime the value for tb_parking_record.exit_time
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setExitTime(Date exitTime) {
        this.exitTime = exitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_parking_record.last_time
     *
     * @return the value of tb_parking_record.last_time
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public String getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_parking_record.last_time
     *
     * @param lastTime the value for tb_parking_record.last_time
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setLastTime(String lastTime) {
        this.lastTime = lastTime == null ? null : lastTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_parking_record.order_id
     *
     * @return the value of tb_parking_record.order_id
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_parking_record.order_id
     *
     * @param orderId the value for tb_parking_record.order_id
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
}