package com.example.demo.entity;

import java.util.Date;

public class TbParkingSpace {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_parking_space.parking_space_id
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    private Integer parkingSpaceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_parking_space.parking_space_location
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    private String parkingSpaceLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_parking_space.parking_space_occupy
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    private Integer parkingSpaceOccupy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_parking_space.parking_space_question
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    private String parkingSpaceQuestion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_parking_space.parking_space_reservation
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    private Integer parkingSpaceReservation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_parking_space.car_id
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    private Integer carId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_parking_space.expire_date
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    private Date expireDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_parking_space
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    public TbParkingSpace(Integer parkingSpaceId, String parkingSpaceLocation, Integer parkingSpaceOccupy, String parkingSpaceQuestion, Integer parkingSpaceReservation, Integer carId, Date expireDate) {
        this.parkingSpaceId = parkingSpaceId;
        this.parkingSpaceLocation = parkingSpaceLocation;
        this.parkingSpaceOccupy = parkingSpaceOccupy;
        this.parkingSpaceQuestion = parkingSpaceQuestion;
        this.parkingSpaceReservation = parkingSpaceReservation;
        this.carId = carId;
        this.expireDate = expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_parking_space
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    public TbParkingSpace() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_parking_space.parking_space_id
     *
     * @return the value of tb_parking_space.parking_space_id
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    public Integer getParkingSpaceId() {
        return parkingSpaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_parking_space.parking_space_id
     *
     * @param parkingSpaceId the value for tb_parking_space.parking_space_id
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    public void setParkingSpaceId(Integer parkingSpaceId) {
        this.parkingSpaceId = parkingSpaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_parking_space.parking_space_location
     *
     * @return the value of tb_parking_space.parking_space_location
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    public String getParkingSpaceLocation() {
        return parkingSpaceLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_parking_space.parking_space_location
     *
     * @param parkingSpaceLocation the value for tb_parking_space.parking_space_location
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    public void setParkingSpaceLocation(String parkingSpaceLocation) {
        this.parkingSpaceLocation = parkingSpaceLocation == null ? null : parkingSpaceLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_parking_space.parking_space_occupy
     *
     * @return the value of tb_parking_space.parking_space_occupy
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    public Integer getParkingSpaceOccupy() {
        return parkingSpaceOccupy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_parking_space.parking_space_occupy
     *
     * @param parkingSpaceOccupy the value for tb_parking_space.parking_space_occupy
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    public void setParkingSpaceOccupy(Integer parkingSpaceOccupy) {
        this.parkingSpaceOccupy = parkingSpaceOccupy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_parking_space.parking_space_question
     *
     * @return the value of tb_parking_space.parking_space_question
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    public String getParkingSpaceQuestion() {
        return parkingSpaceQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_parking_space.parking_space_question
     *
     * @param parkingSpaceQuestion the value for tb_parking_space.parking_space_question
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    public void setParkingSpaceQuestion(String parkingSpaceQuestion) {
        this.parkingSpaceQuestion = parkingSpaceQuestion == null ? null : parkingSpaceQuestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_parking_space.parking_space_reservation
     *
     * @return the value of tb_parking_space.parking_space_reservation
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    public Integer getParkingSpaceReservation() {
        return parkingSpaceReservation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_parking_space.parking_space_reservation
     *
     * @param parkingSpaceReservation the value for tb_parking_space.parking_space_reservation
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    public void setParkingSpaceReservation(Integer parkingSpaceReservation) {
        this.parkingSpaceReservation = parkingSpaceReservation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_parking_space.car_id
     *
     * @return the value of tb_parking_space.car_id
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_parking_space.car_id
     *
     * @param carId the value for tb_parking_space.car_id
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_parking_space.expire_date
     *
     * @return the value of tb_parking_space.expire_date
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    public Date getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_parking_space.expire_date
     *
     * @param expireDate the value for tb_parking_space.expire_date
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }
}