package com.example.demo.entity;

import org.apache.ibatis.annotations.Mapper;

import java.util.Date;
@Mapper
public class TbRuleCustomInterim {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule_custom_interim.interim_rule_id
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    private Integer interimRuleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule_custom_interim.rule_type
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    private String ruleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule_custom_interim.money
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    private Float money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule_custom_interim.car_type
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    private String carType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule_custom_interim.use_date
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    private Date useDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rule_custom_interim
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public TbRuleCustomInterim(Integer interimRuleId, String ruleType, Float money, String carType, Date useDate) {
        this.interimRuleId = interimRuleId;
        this.ruleType = ruleType;
        this.money = money;
        this.carType = carType;
        this.useDate = useDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rule_custom_interim
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public TbRuleCustomInterim() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule_custom_interim.interim_rule_id
     *
     * @return the value of tb_rule_custom_interim.interim_rule_id
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public Integer getInterimRuleId() {
        return interimRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule_custom_interim.interim_rule_id
     *
     * @param interimRuleId the value for tb_rule_custom_interim.interim_rule_id
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public void setInterimRuleId(Integer interimRuleId) {
        this.interimRuleId = interimRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule_custom_interim.rule_type
     *
     * @return the value of tb_rule_custom_interim.rule_type
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public String getRuleType() {
        return ruleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule_custom_interim.rule_type
     *
     * @param ruleType the value for tb_rule_custom_interim.rule_type
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public void setRuleType(String ruleType) {
        this.ruleType = ruleType == null ? null : ruleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule_custom_interim.money
     *
     * @return the value of tb_rule_custom_interim.money
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public Float getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule_custom_interim.money
     *
     * @param money the value for tb_rule_custom_interim.money
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public void setMoney(Float money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule_custom_interim.car_type
     *
     * @return the value of tb_rule_custom_interim.car_type
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule_custom_interim.car_type
     *
     * @param carType the value for tb_rule_custom_interim.car_type
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public void setCarType(String carType) {
        this.carType = carType == null ? null : carType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule_custom_interim.use_date
     *
     * @return the value of tb_rule_custom_interim.use_date
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public Date getUseDate() {
        return useDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule_custom_interim.use_date
     *
     * @param useDate the value for tb_rule_custom_interim.use_date
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public void setUseDate(Date useDate) {
        this.useDate = useDate;
    }
}