package com.example.demo.entity;

public class TbRuleFixedParking {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule_fixed_parking.fixed_rule_id
     *
     * @mbg.generated Wed Apr 08 08:40:13 GMT+08:00 2020
     */
    private Integer fixedRuleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule_fixed_parking.car_type
     *
     * @mbg.generated Wed Apr 08 08:40:13 GMT+08:00 2020
     */
    private String carType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule_fixed_parking.charge_cycle
     *
     * @mbg.generated Wed Apr 08 08:40:13 GMT+08:00 2020
     */
    private String chargeCycle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule_fixed_parking.money
     *
     * @mbg.generated Wed Apr 08 08:40:13 GMT+08:00 2020
     */
    private Float money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule_fixed_parking.description
     *
     * @mbg.generated Wed Apr 08 08:40:13 GMT+08:00 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rule_fixed_parking
     *
     * @mbg.generated Wed Apr 08 08:40:13 GMT+08:00 2020
     */
    public TbRuleFixedParking(Integer fixedRuleId, String carType, String chargeCycle, Float money, String description) {
        this.fixedRuleId = fixedRuleId;
        this.carType = carType;
        this.chargeCycle = chargeCycle;
        this.money = money;
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rule_fixed_parking
     *
     * @mbg.generated Wed Apr 08 08:40:13 GMT+08:00 2020
     */
    public TbRuleFixedParking() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule_fixed_parking.fixed_rule_id
     *
     * @return the value of tb_rule_fixed_parking.fixed_rule_id
     *
     * @mbg.generated Wed Apr 08 08:40:13 GMT+08:00 2020
     */
    public Integer getFixedRuleId() {
        return fixedRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule_fixed_parking.fixed_rule_id
     *
     * @param fixedRuleId the value for tb_rule_fixed_parking.fixed_rule_id
     *
     * @mbg.generated Wed Apr 08 08:40:13 GMT+08:00 2020
     */
    public void setFixedRuleId(Integer fixedRuleId) {
        this.fixedRuleId = fixedRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule_fixed_parking.car_type
     *
     * @return the value of tb_rule_fixed_parking.car_type
     *
     * @mbg.generated Wed Apr 08 08:40:13 GMT+08:00 2020
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule_fixed_parking.car_type
     *
     * @param carType the value for tb_rule_fixed_parking.car_type
     *
     * @mbg.generated Wed Apr 08 08:40:13 GMT+08:00 2020
     */
    public void setCarType(String carType) {
        this.carType = carType == null ? null : carType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule_fixed_parking.charge_cycle
     *
     * @return the value of tb_rule_fixed_parking.charge_cycle
     *
     * @mbg.generated Wed Apr 08 08:40:13 GMT+08:00 2020
     */
    public String getChargeCycle() {
        return chargeCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule_fixed_parking.charge_cycle
     *
     * @param chargeCycle the value for tb_rule_fixed_parking.charge_cycle
     *
     * @mbg.generated Wed Apr 08 08:40:13 GMT+08:00 2020
     */
    public void setChargeCycle(String chargeCycle) {
        this.chargeCycle = chargeCycle == null ? null : chargeCycle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule_fixed_parking.money
     *
     * @return the value of tb_rule_fixed_parking.money
     *
     * @mbg.generated Wed Apr 08 08:40:13 GMT+08:00 2020
     */
    public Float getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule_fixed_parking.money
     *
     * @param money the value for tb_rule_fixed_parking.money
     *
     * @mbg.generated Wed Apr 08 08:40:13 GMT+08:00 2020
     */
    public void setMoney(Float money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule_fixed_parking.description
     *
     * @return the value of tb_rule_fixed_parking.description
     *
     * @mbg.generated Wed Apr 08 08:40:13 GMT+08:00 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule_fixed_parking.description
     *
     * @param description the value for tb_rule_fixed_parking.description
     *
     * @mbg.generated Wed Apr 08 08:40:13 GMT+08:00 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}