package com.example.demo.entity;

public class TbRule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule.rule_id
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private Integer ruleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule.rule_money
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private Double ruleMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule.rule_period
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private String rulePeriod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule.rule_charge_time
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private String ruleChargeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule.rule_location_type
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private String ruleLocationType;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rule
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public TbRule(Integer ruleId, Double ruleMoney, String rulePeriod, String ruleChargeTime, String ruleLocationType) {
        this.ruleId = ruleId;
        this.ruleMoney = ruleMoney;
        this.rulePeriod = rulePeriod;
        this.ruleChargeTime = ruleChargeTime;
        this.ruleLocationType = ruleLocationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rule
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public TbRule() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule.rule_id
     *
     * @return the value of tb_rule.rule_id
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public Integer getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule.rule_id
     *
     * @param ruleId the value for tb_rule.rule_id
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setRuleId(Integer ruleId) {
        this.ruleId = ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule.rule_money
     *
     * @return the value of tb_rule.rule_money
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public Double getRuleMoney() {
        return ruleMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule.rule_money
     *
     * @param ruleMoney the value for tb_rule.rule_money
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setRuleMoney(Double ruleMoney) {
        this.ruleMoney = ruleMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule.rule_period
     *
     * @return the value of tb_rule.rule_period
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public String getRulePeriod() {
        return rulePeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule.rule_period
     *
     * @param rulePeriod the value for tb_rule.rule_period
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setRulePeriod(String rulePeriod) {
        this.rulePeriod = rulePeriod == null ? null : rulePeriod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule.rule_charge_time
     *
     * @return the value of tb_rule.rule_charge_time
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public String getRuleChargeTime() {
        return ruleChargeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule.rule_charge_time
     *
     * @param ruleChargeTime the value for tb_rule.rule_charge_time
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setRuleChargeTime(String ruleChargeTime) {
        this.ruleChargeTime = ruleChargeTime == null ? null : ruleChargeTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule.rule_location_type
     *
     * @return the value of tb_rule.rule_location_type
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public String getRuleLocationType() {
        return ruleLocationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule.rule_location_type
     *
     * @param ruleLocationType the value for tb_rule.rule_location_type
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setRuleLocationType(String ruleLocationType) {
        this.ruleLocationType = ruleLocationType == null ? null : ruleLocationType.trim();
    }
}