package com.example.demo.entity;

public class TbRulePerson {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule_person.person_rule_id
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    private Integer personRuleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule_person.money
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    private Float money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule_person.car_type
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    private String carType;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rule_person
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public TbRulePerson(Integer personRuleId, Float money, String carType) {
        this.personRuleId = personRuleId;
        this.money = money;
        this.carType = carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rule_person
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public TbRulePerson() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule_person.person_rule_id
     *
     * @return the value of tb_rule_person.person_rule_id
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public Integer getPersonRuleId() {
        return personRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule_person.person_rule_id
     *
     * @param personRuleId the value for tb_rule_person.person_rule_id
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public void setPersonRuleId(Integer personRuleId) {
        this.personRuleId = personRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule_person.money
     *
     * @return the value of tb_rule_person.money
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public Float getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule_person.money
     *
     * @param money the value for tb_rule_person.money
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public void setMoney(Float money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule_person.car_type
     *
     * @return the value of tb_rule_person.car_type
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule_person.car_type
     *
     * @param carType the value for tb_rule_person.car_type
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public void setCarType(String carType) {
        this.carType = carType == null ? null : carType.trim();
    }
}