package com.example.demo.entity;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public class TbRuleCommonBasic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule_common_basic.rule_id
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    private Integer ruleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule_common_basic.rule_type
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    private String ruleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule_common_basic.money
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    private Float money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule_common_basic.car_type
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    private String carType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule_common_basic.zone_type
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    private String zoneType;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rule_common_basic
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public TbRuleCommonBasic(Integer ruleId, String ruleType, Float money, String carType, String zoneType) {
        this.ruleId = ruleId;
        this.ruleType = ruleType;
        this.money = money;
        this.carType = carType;
        this.zoneType = zoneType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rule_common_basic
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public TbRuleCommonBasic() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule_common_basic.rule_id
     *
     * @return the value of tb_rule_common_basic.rule_id
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public Integer getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule_common_basic.rule_id
     *
     * @param ruleId the value for tb_rule_common_basic.rule_id
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public void setRuleId(Integer ruleId) {
        this.ruleId = ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule_common_basic.rule_type
     *
     * @return the value of tb_rule_common_basic.rule_type
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public String getRuleType() {
        return ruleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule_common_basic.rule_type
     *
     * @param ruleType the value for tb_rule_common_basic.rule_type
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public void setRuleType(String ruleType) {
        this.ruleType = ruleType == null ? null : ruleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule_common_basic.money
     *
     * @return the value of tb_rule_common_basic.money
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public Float getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule_common_basic.money
     *
     * @param money the value for tb_rule_common_basic.money
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public void setMoney(Float money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule_common_basic.car_type
     *
     * @return the value of tb_rule_common_basic.car_type
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule_common_basic.car_type
     *
     * @param carType the value for tb_rule_common_basic.car_type
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public void setCarType(String carType) {
        this.carType = carType == null ? null : carType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule_common_basic.zone_type
     *
     * @return the value of tb_rule_common_basic.zone_type
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public String getZoneType() {
        return zoneType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule_common_basic.zone_type
     *
     * @param zoneType the value for tb_rule_common_basic.zone_type
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    public void setZoneType(String zoneType) {
        this.zoneType = zoneType == null ? null : zoneType.trim();
    }

    @Override
    public String toString() {
        return "TbRuleCommonBasic{" +
                "ruleId=" + ruleId +
                ", ruleType='" + ruleType + '\'' +
                ", money=" + money +
                ", carType='" + carType + '\'' +
                ", zoneType='" + zoneType + '\'' +
                '}';
    }
}