package com.example.demo.entity;

import java.util.Date;

public class TbStaffDuty {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_staff_duty.staff_duty_id
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    private Integer staffDutyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_staff_duty.starting_time
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    private Date startingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_staff_duty.ending_time
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    private Date endingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_staff_duty.description
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_staff_duty
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    public TbStaffDuty(Integer staffDutyId, Date startingTime, Date endingTime, String description) {
        this.staffDutyId = staffDutyId;
        this.startingTime = startingTime;
        this.endingTime = endingTime;
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_staff_duty
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    public TbStaffDuty() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff_duty.staff_duty_id
     *
     * @return the value of tb_staff_duty.staff_duty_id
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    public Integer getStaffDutyId() {
        return staffDutyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff_duty.staff_duty_id
     *
     * @param staffDutyId the value for tb_staff_duty.staff_duty_id
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    public void setStaffDutyId(Integer staffDutyId) {
        this.staffDutyId = staffDutyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff_duty.starting_time
     *
     * @return the value of tb_staff_duty.starting_time
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    public Date getStartingTime() {
        return startingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff_duty.starting_time
     *
     * @param startingTime the value for tb_staff_duty.starting_time
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    public void setStartingTime(Date startingTime) {
        this.startingTime = startingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff_duty.ending_time
     *
     * @return the value of tb_staff_duty.ending_time
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    public Date getEndingTime() {
        return endingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff_duty.ending_time
     *
     * @param endingTime the value for tb_staff_duty.ending_time
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    public void setEndingTime(Date endingTime) {
        this.endingTime = endingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff_duty.description
     *
     * @return the value of tb_staff_duty.description
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff_duty.description
     *
     * @param description the value for tb_staff_duty.description
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}