package com.example.demo.entity;

import java.util.Date;

public class TbStaffDuty {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_staff_duty.staff_duty_id
     *
     * @mbg.generated Sat Mar 07 15:39:05 GMT+08:00 2020
     */
    private Integer staffDutyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_staff_duty.starting_time
     *
     * @mbg.generated Sat Mar 07 15:39:05 GMT+08:00 2020
     */
    private Date startingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_staff_duty.ending_time
     *
     * @mbg.generated Sat Mar 07 15:39:05 GMT+08:00 2020
     */
    private Date endingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_staff_duty.lasting_time
     *
     * @mbg.generated Sat Mar 07 15:39:05 GMT+08:00 2020
     */
    private Date lastingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_staff_duty.staff_task_id
     *
     * @mbg.generated Sat Mar 07 15:39:05 GMT+08:00 2020
     */
    private Integer staffTaskId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_staff_duty
     *
     * @mbg.generated Sat Mar 07 15:39:05 GMT+08:00 2020
     */
    public TbStaffDuty(Integer staffDutyId, Date startingTime, Date endingTime, Date lastingTime, Integer staffTaskId) {
        this.staffDutyId = staffDutyId;
        this.startingTime = startingTime;
        this.endingTime = endingTime;
        this.lastingTime = lastingTime;
        this.staffTaskId = staffTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_staff_duty
     *
     * @mbg.generated Sat Mar 07 15:39:05 GMT+08:00 2020
     */
    public TbStaffDuty() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff_duty.staff_duty_id
     *
     * @return the value of tb_staff_duty.staff_duty_id
     *
     * @mbg.generated Sat Mar 07 15:39:05 GMT+08:00 2020
     */
    public Integer getStaffDutyId() {
        return staffDutyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff_duty.staff_duty_id
     *
     * @param staffDutyId the value for tb_staff_duty.staff_duty_id
     *
     * @mbg.generated Sat Mar 07 15:39:05 GMT+08:00 2020
     */
    public void setStaffDutyId(Integer staffDutyId) {
        this.staffDutyId = staffDutyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff_duty.starting_time
     *
     * @return the value of tb_staff_duty.starting_time
     *
     * @mbg.generated Sat Mar 07 15:39:05 GMT+08:00 2020
     */
    public Date getStartingTime() {
        return startingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff_duty.starting_time
     *
     * @param startingTime the value for tb_staff_duty.starting_time
     *
     * @mbg.generated Sat Mar 07 15:39:05 GMT+08:00 2020
     */
    public void setStartingTime(Date startingTime) {
        this.startingTime = startingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff_duty.ending_time
     *
     * @return the value of tb_staff_duty.ending_time
     *
     * @mbg.generated Sat Mar 07 15:39:05 GMT+08:00 2020
     */
    public Date getEndingTime() {
        return endingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff_duty.ending_time
     *
     * @param endingTime the value for tb_staff_duty.ending_time
     *
     * @mbg.generated Sat Mar 07 15:39:05 GMT+08:00 2020
     */
    public void setEndingTime(Date endingTime) {
        this.endingTime = endingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff_duty.lasting_time
     *
     * @return the value of tb_staff_duty.lasting_time
     *
     * @mbg.generated Sat Mar 07 15:39:05 GMT+08:00 2020
     */
    public Date getLastingTime() {
        return lastingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff_duty.lasting_time
     *
     * @param lastingTime the value for tb_staff_duty.lasting_time
     *
     * @mbg.generated Sat Mar 07 15:39:05 GMT+08:00 2020
     */
    public void setLastingTime(Date lastingTime) {
        this.lastingTime = lastingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff_duty.staff_task_id
     *
     * @return the value of tb_staff_duty.staff_task_id
     *
     * @mbg.generated Sat Mar 07 15:39:05 GMT+08:00 2020
     */
    public Integer getStaffTaskId() {
        return staffTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff_duty.staff_task_id
     *
     * @param staffTaskId the value for tb_staff_duty.staff_task_id
     *
     * @mbg.generated Sat Mar 07 15:39:05 GMT+08:00 2020
     */
    public void setStaffTaskId(Integer staffTaskId) {
        this.staffTaskId = staffTaskId;
    }
}