package com.example.demo.entity;

public class TbUserAmount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_amount.user_amount_id
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private Integer userAmountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_amount.user_id
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_amount.user_amount_balance
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private Float userAmountBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_amount.user_amount_gift_money
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    private Float userAmountGiftMoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_amount
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public TbUserAmount(Integer userAmountId, Integer userId, Float userAmountBalance, Float userAmountGiftMoney) {
        this.userAmountId = userAmountId;
        this.userId = userId;
        this.userAmountBalance = userAmountBalance;
        this.userAmountGiftMoney = userAmountGiftMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_amount
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public TbUserAmount() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_amount.user_amount_id
     *
     * @return the value of tb_user_amount.user_amount_id
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public Integer getUserAmountId() {
        return userAmountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_amount.user_amount_id
     *
     * @param userAmountId the value for tb_user_amount.user_amount_id
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setUserAmountId(Integer userAmountId) {
        this.userAmountId = userAmountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_amount.user_id
     *
     * @return the value of tb_user_amount.user_id
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_amount.user_id
     *
     * @param userId the value for tb_user_amount.user_id
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_amount.user_amount_balance
     *
     * @return the value of tb_user_amount.user_amount_balance
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public Float getUserAmountBalance() {
        return userAmountBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_amount.user_amount_balance
     *
     * @param userAmountBalance the value for tb_user_amount.user_amount_balance
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setUserAmountBalance(Float userAmountBalance) {
        this.userAmountBalance = userAmountBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_amount.user_amount_gift_money
     *
     * @return the value of tb_user_amount.user_amount_gift_money
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public Float getUserAmountGiftMoney() {
        return userAmountGiftMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_amount.user_amount_gift_money
     *
     * @param userAmountGiftMoney the value for tb_user_amount.user_amount_gift_money
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    public void setUserAmountGiftMoney(Float userAmountGiftMoney) {
        this.userAmountGiftMoney = userAmountGiftMoney;
    }
}