package com.example.demo.mapper;

import com.example.demo.entity.TbCoupon;
import org.apache.ibatis.annotations.Mapper;

import java.util.Date;
import java.util.List;

@Mapper
public interface TbCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    int insert(TbCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    int insertSelective(TbCoupon record);

    int addRowByInfo(float coupon_amount,
                     int coupon_count,
                     String coupon_location,
                     int coupon_usage_count,
                     Date starting_time,
                     Date ending_time,
                     String coupon_situation);
    List<TbCoupon> selectAll(int pageNum, int page);
}