package com.example.demo.mapper;

import com.example.demo.entity.TbCoupon;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface TbCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    int insert(TbCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    int insertSelective(TbCoupon record);
}