package com.example.demo.mapper;

import com.example.demo.entity.TbOrder;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface TbOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated Sat Apr 18 19:53:53 GMT+08:00 2020
     */
    int insert(TbOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated Sat Apr 18 19:53:53 GMT+08:00 2020
     */
    int insertSelective(TbOrder record);

    int addRowByInfo(TbOrder tbOrder);

    float selectTotalCount(@Param(value = "date") String starting_time);
    int selectRowCount(@Param(value = "date") String starting_time);

    List<TbOrder> selectAll(int pageNum,int page);

    List<TbOrder> selectOrderByUserName(String username);
}