package com.example.demo.mapper;

import com.example.demo.entity.TbParkingLot;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface TbParkingLotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_parking_lot
     *
     * @mbg.generated Fri Apr 17 19:17:36 GMT+08:00 2020
     */
    int insert(TbParkingLot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_parking_lot
     *
     * @mbg.generated Fri Apr 17 19:17:36 GMT+08:00 2020
     */
    int insertSelective(TbParkingLot record);

    int addRowByInfo(String parking_lot_name, @Param(value = "space_number") int parking_space_number, @Param(value = "parking_lot_level") String zone_type, String pay_setting, String print_setting, String rule_setting);

    int updateRowByInfo(String parking_lot_name,@Param(value = "space_number")int parking_space_number,@Param(value = "parking_lot_level") String zone_type,String pay_setting,String print_setting,String rule_setting);

    List<TbParkingLot> selectRowById(int id);
}