package com.example.demo.mapper;

import com.example.demo.entity.TbOrder;
import com.example.demo.entity.TbParkingRecord;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.lang.Nullable;

import java.util.Date;
import java.util.List;

@Mapper
public interface TbParkingRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_parking_record
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    int insert(TbParkingRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_parking_record
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    int insertSelective(TbParkingRecord record);

    int addRowByInfo(String car_plate_num, String enter_time);

    List<TbParkingRecord> selectEnter(String date, int pageNum, int page);

    List<TbParkingRecord> selectOuter(String date, int pageNum, int page);

    List<TbParkingRecord> selectAll(int pageNum, int page);

    List<TbParkingRecord> selectAllByEnter(int pageNum, int page);

    List<TbParkingRecord> selectAllByOuter(int pageNum, int page);

    /**
     * 查找尚未出场的车牌
     *
     * @return
     */
    List<TbParkingRecord> selectCar();

    int updateByOuter(String order_car_number, String starting_time, String date, int order_id);

    List<TbParkingRecord> selectDutyAll(@Param(value = "date") String start_time, int pageNum, int page);

    int selectAll();

    int selectCountEnter(@Param(value = "date") String start_time);

    int selectCountOuter(@Param(value = "date") String start_time);

    /**
     * 查找场内停车数量
     *
     * @return
     */
    int selectOccupyNum();

    int selectNumByDate(String date);

    TbParkingRecord selectEnterTimeByCarPlate(String order_car_number);

    List<TbParkingRecord> selectTenDayDate(int number);

    List<TbParkingRecord> select24hourDate(int number);

    List<TbParkingRecord> selectRowByCarNum(String car_number);

    int selectExitCarByDate(String starting_time, String ending_time);

    int selectEnterCarByDate(String starting_time, String ending_time);


    List<TbParkingRecord> selectCountByDate(String starting_time, String ending_time);

    int selectAllByDate(String starting_time, String ending_time);

    List<TbParkingRecord> selectInterimCarByDate(String starting_time, String ending_time);

}