package com.example.demo.mapper;

import com.example.demo.entity.TbOrder;
import com.example.demo.entity.TbParkingSpace;

import java.util.Date;
import java.util.List;

public interface TbParkingSpaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_parking_space
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    int insert(TbParkingSpace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_parking_space
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    int insertSelective(TbParkingSpace record);

    List<TbParkingSpace> selectAll(int pageNum, int page);

    List<TbParkingSpace> selectSpaceById(String user_id);

    int addParkingSpace(String parkingSpaceArea);

    int updateParkingSpace(String car_id, String expire_date, String parking_space_id);

    int addateParkingSpace(String car_id, String expire_date, String parking_space_id);

    List<TbParkingSpace> selectNotOccupy();

    TbParkingSpace selectRowById(String parking_space_id);

    List<TbParkingSpace> selectAllByFurryStr(String parking_space_key_word_title, String parking_space_key_word, String parking_space_searchDate, int pageNum, int page);

    List<TbParkingSpace> selectExpireDateByCar(String car_plate_num);

    int selectCarSpaceNumberByUserId(String userId);

    List<TbParkingSpace> selectAllByUserId(String userId);
}