package com.example.demo.mapper;

import com.example.demo.entity.TbParkingSpace;

public interface TbParkingSpaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_parking_space
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    int insert(TbParkingSpace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_parking_space
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    int insertSelective(TbParkingSpace record);
}