package com.example.demo.mapper;

import com.example.demo.entity.TbRuleCustomInterim;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface TbRuleCustomInterimMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rule_custom_interim
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    int insert(TbRuleCustomInterim record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rule_custom_interim
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    int insertSelective(TbRuleCustomInterim record);
}