package com.example.demo.mapper;

import com.example.demo.entity.TbRulePerson;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface TbRulePersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rule_person
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    int insert(TbRulePerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_rule_person
     *
     * @mbg.generated Wed Apr 08 08:16:45 GMT+08:00 2020
     */
    int insertSelective(TbRulePerson record);
}