package com.example.demo.mapper;

import com.example.demo.entity.TbStaffTask;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface TbStaffTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_staff_task
     *
     * @mbg.generated Sat Mar 07 15:39:05 GMT+08:00 2020
     */
    int insert(TbStaffTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_staff_task
     *
     * @mbg.generated Sat Mar 07 15:39:05 GMT+08:00 2020
     */
    int insertSelective(TbStaffTask record);

    /**
     * 根据员工id查找所有的任务
     * @param staff_id
     * @return
     */

    int selectCountByStaffId(@Param("staff_id") String staff_id);

    /**
     * 根据员工id查找未完成的任务
     * @param staff_id
     * @return
     */
    List<TbStaffTask> selectUnfinishedTask(@Param("staff_id") String staff_id);

    /**
     * 查询所有任务
     * @return
     */
    List<TbStaffTask> selectAll();
}