package com.example.demo.mapper;

import com.example.demo.entity.TbStaffDuty;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TbStaffDutyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_staff_duty
     *
     * @mbg.generated Wed Apr 22 12:38:47 GMT+08:00 2020
     */
    int insert(TbStaffDuty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_staff_duty
     *
     * @mbg.generated Wed Apr 22 12:38:47 GMT+08:00 2020
     */
    int insertSelective(TbStaffDuty record);

    /**
     * 新增加值班记录
     *
     * @param staff_id
     * @param date
     * @return
     */
    int addRowByInfo(int staff_id, String date, int staff_task_id);

    /**
     * 查找当前是否有人值班
     *
     * @return
     */
    int selectDutyExist();

    /**
     * 查找当前值班的开始时间
     *
     * @return
     */
    String selectStartingTime();

    /**
     * 下班
     *
     * @param date
     * @return
     */
    int updateRowByInfo(String date);

    /**
     * 查询第一条数据
     *
     * @return
     */
    TbStaffDuty selectLastRow();

    /**
     * 查找所有数据
     */
    List<TbStaffDuty> selectAll(int pageNum, int page);

    /**
     * 根据id查找记录
     * @param staffDutyId
     * @return
     */
    TbStaffDuty selectRowById(String staffDutyId);
}