package com.example.demo.mapper;

import com.example.demo.entity.TbStaffDuty;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface TbStaffDutyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_staff_duty
     *
     * @mbg.generated Sat Mar 07 15:39:05 GMT+08:00 2020
     */
    int insert(TbStaffDuty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_staff_duty
     *
     * @mbg.generated Sat Mar 07 15:39:05 GMT+08:00 2020
     */
    int insertSelective(TbStaffDuty record);
}