package com.example.demo.mapper;

import com.example.demo.entity.TbStaff;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface TbStaffMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_staff
     *
     * @mbg.generated Sat Mar 07 15:53:12 GMT+08:00 2020
     */
    int insert(TbStaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_staff
     *
     * @mbg.generated Sat Mar 07 15:53:12 GMT+08:00 2020
     */
    int insertSelective(TbStaff record);


    /**
     * 根据用户名和密码是否匹配
     *
     * @param name
     * @param pwd
     * @return
     */
    int selectForLogin(@Param("staff_name") String name, @Param("staff_login_pwd") String pwd);

    /**
     * 根据用户名查询是否存在
     *
     * @param name
     * @return
     */
    int selectByUserName(@Param("staff_name") String name);

    /**
     * 根据用户名查找id
     * @param name
     * @return
     */
    int selectIdByName(@Param("staff_name") String name);

    List<TbStaff> selectAll();
}