package com.example.demo.mapper;

import com.example.demo.entity.TbStaffDuty;

public interface TbStaffDutyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_staff_duty
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    int insert(TbStaffDuty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_staff_duty
     *
     * @mbg.generated Wed Apr 08 08:30:07 GMT+08:00 2020
     */
    int insertSelective(TbStaffDuty record);
}