package com.example.demo.mapper;

import com.example.demo.entity.TbUserMonthlyCard;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface TbUserMonthlyCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_monthly_card
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    int insert(TbUserMonthlyCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_monthly_card
     *
     * @mbg.generated Tue Feb 25 17:41:08 GMT+08:00 2020
     */
    int insertSelective(TbUserMonthlyCard record);
}